### ISSUE TITLE
See sharp with C#

### ISSUE THREAD

**Issue by vertonghenb** [HOGENT-Web/csharp#14]
#### Chapter 2
- [x] C# Fundamentals

#### Chapter 3
- [x] Model & Unit Testing
- [x] Delegates
- [x] Visual Studio Solution
- [x] What's new in C# 9

##### TODO:
- [ ] Add [Shouldly](https://github.com/shouldly/shouldly) for testing 
- [ ] Add [ValueObject](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects) Implementation for AccountNumber
- [ ] Add [Records](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/records)
- [ ] Add [Records vs ValueObjects](https://enterprisecraftsmanship.com/posts/csharp-records-value-objects/)
- [ ] Add `Action` as Delegate Type

### Material
- Web III

**Comment by vertonghenb** [comment]
@thomasaelbrecht Can you check the TODO and see if you approve?

**Comment by thomasaelbrecht** [comment]
@vertonghenb Do I need to add these topics or will you?
